# Generated by Django 3.2.16 on 2023-01-05 13:15

import ImageApi.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image', models.ImageField(blank=True, storage=ImageApi.storage.MediaStorage(), upload_to='ImageApi.storage.MediaStorage')),
            ],
        ),
    ]
