# Generated by Django 3.2.16 on 2023-01-08 14:46

import ImageApi.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, storage=ImageApi.storage.MediaStorage(), upload_to='test'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(100)]),
        ),
    ]
